### ISSUE TITLE
librarian can't handle tar archives which contain very long paths

### ISSUE THREAD

**Issue by databus23** [applicationsonline/librarian#128]
I just noticed that librarian fails to unpack cookbook tarballs properly which contain a path  longer than 100 characters.

After a little bit of reading I had to learn that the tar archive header originally didn't support paths with filenames longer then 100 characters. Since then several additions have been added to tar implementations to accommodate longer filenames (e.g. @LongLink in _GNU TAR_ and PaxHeaders in _BSD TAR_).

The problems seems to be the rather outdated archive-tar-minitar gem which doesn't support any of these additions to tar and subsequently mangles the filenames of elements with a path longer then 100 characters during extraction.

In both cases (@LongLink and PaxHeaders ) `librarian install` raises the following exception:

```
lib/librarian/chef/source/site.rb:271:in `unpack_package!': The package archive has too many children! 
```

Thats because archive-tar-minitar creates additional files in the extraction root.

The following gist shortly demonstrates the problem on OSX: https://gist.github.com/databus23/4715855

**Comment by yfeldblum** [comment]
That's quite entertaining....

**Comment by yfeldblum** [comment]
Want to see if minitar ([gem](https://rubygems.org/gems/minitar), [github](https://github.com/atoulme/minitar)) works better?

**Comment by databus23** [comment]
This fork of archive-tar-minitar actually contains a fix for the gnu tar format (@LongLink) with  https://github.com/atoulme/minitar/commit/2b8b4a37fbf9b88ee12f21faf1fed32beda322f4 

Other tar archive formats like pax which is the default on OSX still fail. While tar on OSX is able to extract gnu tar archives correctly it doesn't seem to support creating gnu tar archives with the `--format`.

So using [minitar](https://github.com/atoulme/minitar) instead of [archive-tar-minitar](http://rubyforge.org/projects/ruwiki/) would solve the issue for tar archives created on linux which in general seem to default to the gnu tar format.

It think to solve this issue properly librarian would need to shell out because of the lack of a decent opensource pure ruby tar library but on the other hand that sucks for platform independence (especially for windows I guess).

**Comment by yfeldblum** [comment]
It's best for `librarian` to avoid shelling out, and to stick to stable interfaces of standard Ruby libraries when possible. Even if those libraries are limited in their edge cases, it's better than trying to handle varying CLI interfaces and trying to do process management. Windows, while not something I test on, is an important use-case.

**Comment by databus23** [comment]
I agree.

To improve the situation at least partially (for gnu tar/linux) how about switching from archive-tar-minitar to minitar?

**Comment by databus23** [comment]
Hmm, I just noticed that `vagrant` has a direct dependency to `archive-tar-minitar`. Switching to `mintar`would complicate things when using `librarian` together with `vagrant`.

**Comment by databus23** [comment]
I just had another occurrence of this bug.

Now that vagrant ships as an installer with its own ruby environment the gem conflict is not an issue anymore.

I would suggest changing the dependency from `archive-tar-minitar` to `minitar`.
This improves the situation at least for GNU Tar archives.

The similar tool berkshelf also [favored minitar](https://github.com/RiotGames/berkshelf/blob/master/berkshelf.gemspec#L40).

**Comment by databus23** [comment]
bump.

how about switching to `minitar`?

**Comment by Kuckkuck** [comment]
will this bug ever be fixed. I am running into the same issue:
../vendor/bundle/ruby/1.9.1/gems/librarian-chef-0.0.1/lib/librarian/chef/source/site.rb:271:in `unpack_package!': The package archive has too many children! (RuntimeError)

+1

**Comment by rkolless** [comment]
I have the same problem here that the path depth reaches the limit and some cookbook can´t be installed by librarian.
Would be nice to have this problem fixed.

+1

**Comment by yfeldblum** [comment]
Fixed in applicationsonline/librarian-chef@52ebf7cfa1be41116c2fd70949e16405cdca1c9e.

**Comment by ror6ax** [comment]
Looks still broken to me:

/home/ror6ax/.rvm/gems/ruby-2.2.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:309:in `unpack_package!': The package archive has too many children! (RuntimeError)

gem list librarian-chef                                                                ✭

**\* LOCAL GEMS ***

librarian-chef (0.0.4)

**Comment by diegows** [comment]
Same problem here. I have minitar installed.

**Comment by markeroon** [comment]
I'm running into this too.

```
librarian-chef install --clean
/Library/Ruby/Gems/2.0.0/gems/librarian-chef-0.0.4/lib/librarian/chef/source/site.rb:309:in `unpack_package!': The package archive has too many children! (RuntimeError)
```

**Comment by pecigonzalo** [comment]
I ran into the same issue, making a junction point to the folder and editing .bundle/config with the full path of the junction seems to work.
Alternatively you can use fullpath to the junction point.

**Comment by realchrisolin** [comment]
I know this is fairly old, but this issue is still present in modern versions of librarian. I'm not sure what I can do to work around it either.

```
C:/Users/Chris Olin/.vagrant.d/gems/2.3.4/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/site.rb:309:in `unpack_package!': The package archive has too many children! (RuntimeError)
        from C:/Users/Chris Olin/.vagrant.d/gems/2.3.4/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/site.rb:224:in `cache_version_uri_unpacked!'
        from C:/Users/Chris Olin/.vagrant.d/gems/2.3.4/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/site.rb:93:in `block in version_uri_manifest'
        from C:/Users/Chris Olin/.vagrant.d/gems/2.3.4/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/site.rb:382:in `memo'
        from C:/Users/Chris Olin/.vagrant.d/gems/2.3.4/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/site.rb:92:in `version_uri_manifest'
        from C:/Users/Chris Olin/.vagrant.d/gems/2.3.4/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/site.rb:88:in `version_manifest'
        from C:/Users/Chris Olin/.vagrant.d/gems/2.3.4/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/site.rb:54:in `version_dependencies'
        from C:/Users/Chris Olin/.vagrant.d/gems/2.3.4/gems/librarian-chef-nochef-0.2.0/lib/librarian/chef/source/site.rb:463:in `fetch_dependencies'
```

**Comment by mjako78** [comment]
Same for me.  
I'm trying to use **system** cookbook and I run in this bug.

**Comment by marcelino056** [comment]
Same here

```Log
The package archive has too many children! (RuntimeError)
```

**Comment by matedemorphy** [comment]
Same issue:
Vagrant File:
`# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
REQUIRED_PLUGINS        = %w(vagrant-vbguest vagrant-librarian-chef-nochef)

plugins_to_install = REQUIRED_PLUGINS.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing required plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting. Please read the Bike Index README."
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use Ubuntu Bionic 16.04 64-bit as operating system
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20190914.0.0"
  # Configure the virtual machine to use 1.5GB of RAM
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1536"]
  end
  # Forward the Rails server default port to the host
  config.vm.network :forwarded_port, guest: 3005, host: 3005
  config.vm.network :forwarded_port, host: 1085, guest: 1085 
  config.vm.network :forwarded_port, host: 5005, guest: 5005
  # Use Chef Solo to provision our virtual machine
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks", "site-cookbooks"]

    chef.add_recipe "apt"
    chef.add_recipe "build-essential"
    chef.add_recipe "system::install_packages"
    chef.add_recipe "ruby_build"
    chef.add_recipe "ruby_rbenv::user"
    chef.add_recipe "ruby_rbenv::user_install"
    chef.add_recipe "vim"
    chef.add_recipe "postgresql::server"
    chef.add_recipe "postgresql::client"
    chef.add_recipe "redisio"
    chef.add_recipe "redisio::enable"
    chef.add_recipe "heroku-toolbelt"
    chef.add_recipe "nodejs::install_from_source"
    
    chef.arguments = "--chef-license accept"

    chef.json = {
      rbenv: {
        user_installs: [{
            "user": 'ubuntu',
            "rubies": ["2.5.3", 'jruby-9.2.8.0'],
            "global": "2.5.3",
            "gems": {
            "2.5.3" => [{ name: "bundler" }]
          }
        }]
      },
      system: {
        packages: {
          install: [
          "tar",
          "curl",
          "git",
          "make",
          "tree",
          "htop",
          "software-properties-common",
          "libxslt-dev",
          "libxml2-dev",
          "libgmp-dev",
          "lib1g-dev",
          "libssl-dev",
          "libreadline6-dev",
          "libyaml-dev",
          "libfontconfig1",
          "libncurses5-dev",
          "unzip",
          "wget",
          "python",
          "python-software-properties"
          ]
        }
      },
      postgresql: {
        :pg_hba => [
          { "type": "local", "db": "all", "user": "postgres",   "addr": "",             "method": "peer" },
          { "type": "local", "db": "all", "user": "all",        "addr": "",             "method": "peer" },
          { "type": "host",  "db": "all", "user": "all",        "addr": "127.0.0.1/32", "method": "md5" },
          { "type": "host",  "db": "all", "user": "all",        "addr": "::1/128",      "method": "md5" }
        ],
        :config => {
          "listen_addresses": "*",
          "port": "5432"
        },
        :users => [{
          "username": "postgres",
          "password": "postgres",
          "superuser": true,
          "replication": false,
          "createdb": true,
          "createrole": false,
          "inherit": false,
          "login": true
        }]
      },
      nodejs: {
        "version": "10.16.3",
        "install_method": "source",
        "npm" => "6.9.0"
      }
    }
  end
end`

Cheffile:
`site "https://supermarket.chef.io/"

cookbook 'apt'
cookbook 'build-essential'
cookbook 'system'
cookbook 'vim'
cookbook 'ruby_build', git: 'https://github.com/sous-chefs/ruby_build'
cookbook 'ruby_rbenv', git: 'https://github.com/sous-chefs/ruby_rbenv'
cookbook 'postgresql', git: 'https://github.com/matedemorphy/chef-postgresql'
cookbook 'heroku-toolbelt'
cookbook 'nodejs', git: 'https://github.com/redguide/nodejs'
cookbook 'redisio', git: 'https://github.com/sous-chefs/redisio'`
